
const ETH_GOERLI = 5;
const ETH_MAINNET = 1;

const BSC_TESTNET = 97;
const BSC_MAINNET = 56;
const BSC_API_KEY = '84QSIJWX1BV4P9B9BFFTUG46MRPIUY2U2B';
const ETH_API_KEY = '';

module.exports = {
    ETH_GOERLI,
    ETH_MAINNET,
    BSC_TESTNET,
    BSC_MAINNET,
    BSC_API_KEY,
    ETH_API_KEY
}