
GET http://localhost:5000/endpoint/user 
content-type: application/json

{
"merchant":"111111"
}

###
POST http://localhost:5000/endpoint/create-wallet 
content-type: application/json

{
    "merchant":"111111",
      "userId":"723409284",
      "mode":null

}

###
GET http://localhost:5000/endpoint/transaction 
content-type: application/json

{
    "merchant":"111111"
    }

###
DELETE  http://localhost:5000/api/merchant 
content-type: application/json

{
        "partner_code":"123456"

}
